namespace sinecoserveract.Utilidades
{
    public class htmlconten
    {
        public string HtmlContenpass(string email, string token, string usuario)
        {
            return $"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>																																								" +
                    $"<html xmlns='http://www.w3.org/1999/xhtml'>                                                                                                                                                                                                                                           " +
                    $"<head>                                                                                                                                                                                                                                                                                " +
                    $"<meta name='viewport' content='width=device-width' />                                                                                                                                                                                                                                 " +
                    $"<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />                                                                                                                                                                                                                 " +
                    $"<title>Recuperacion de Clave</title>                                                                                                                                                                                                                                     				" +
                    $"</head>                                                                                                                                                                                                                                                                               " +
                    $"<body style='margin:0px; background: #f8f8f8; '>                                                                                                                                                                                                                                      " +
                    $"<div width='100%' style='background: #f8f8f8; padding: 0px 0px; font-family:arial; line-height:28px; height:100%;  width: 100%; color: #514d6a;'>                                                                                                                                     " +
                    $"  <div style='max-width: 700px; padding:50px 0;  margin: 0px auto; font-size: 14px'>                                                                                                                                                                                                  " +
                    $"    <table border='0' cellpadding='0' cellspacing='0' style='width: 100%; margin-bottom: 20px'>                                                                                                                                                                                       " +
                    $"      <tbody>                                                                                                                                                                                                                                                                         " +
                    $"        <tr>                                                                                                                                                                                                                                                                          " +
                    $"          <td style='vertical-align: top; padding-bottom:15px;' align='center'><a href='https://www.fcivalledelcauca.com.co/' target='_blank'><img src='https://www.fcivalledelcauca.com.co/assets/images/home/fcivalle.png' alt='FCI Valle del Cauca' style='border:none; width:70%'><br/>  " +
                    $"            </td>                                                                                                                                                                                                                                                                     " +
                    $"        </tr>                                                                                                                                                                                                                                                                         " +
                    $"      </tbody>                                                                                                                                                                                                                                                                        " +
                    $"    </table>                                                                                                                                                                                                                                                                          " +
                    $"    <div style='padding: 40px; background: #fff;'>                                                                                                                                                                                                                                    " +
                    $"      <table border='0' cellpadding='0' cellspacing='0' style='width: 100%;'>                                                                                                                                                                                                         " +
                    $"        <tbody>                                                                                                                                                                                                                                                                       " +
                    $"          <tr>                                                                                                                                                                                                                                                                        " +
                    $"            <td style='border-bottom:1px solid #f6f6f6;'><h1 style='font-size:14px; font-family:arial; margin:0px; font-weight:bold;'>Hola, {usuario.ToUpper()} </h1>                                                                                                        " +
                    $"          </tr>                                                                                                                                                                                                                                                                       " +
                    $"          <tr>                                                                                                                                                                                                                                                                        " +
                    $"            <td style='padding:10px 0 30px 0;'><p>Hemos recibido tu solicitud para el cambio de clave. Para realizarlo haz clic en el botón <b>Restablecer Contraseña.</b> Por seguridad te recomendamos realizar periódicamente el cambio de clave a través del sitio web.</p>     " +
                    $"              <center>                                                                                                                                                                                                                                                                " +
                    $"                <a href='https://www.fcivalledelcauca.com.co/resetpass/{email}/{token}' style='display: inline-block; padding: 11px 30px; margin: 20px 0px 30px; font-size: 15px; color: #fff; background: #0B9FA5; border-radius: 60px; text-decoration:none;'>Restablecer Contraseña</a>  " +
                    $"              </center>                                                                                                                                                                                                                                                               " +
                    $"              <b>Cordialmente, Fortalecimiento de las Capacidades Institucionales</b> </td>                                                                                                                                                                                                                          " +
                    $"          </tr>                                                                                                                                                                                                                                                                       " +
                    $"          <tr>                                                                                                                                                                                                                                                                        " +
                    $"            <td  style='border-top:1px solid #f6f6f6; padding-top:20px; color:#777'>Si tienes alguna duda comunícate con la línea de atención 310 430 50 00.</td>                                                                                                           " +
                    $"          </tr>                                                                                                                                                                                                                                                                       " +
                    $"        </tbody>                                                                                                                                                                                                                                                                      " +
                    $"      </table>                                                                                                                                                                                                                                                                        " +
                    $"    </div>                                                                                                                                                                                                                                                                            " +
                    $"  </div>                                                                                                                                                                                                                                                                              " +
                    $"</div>                                                                                                                                                                                                                                                                                " +
                    $"</body>                                                                                                                                                                                                                                                                               " +
                    $"</html>                                                                                                                                                                                                                                                                               ";




        }

        public string HtmlContenwelcome(string email, string usuario)
        {
            return $"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>																																										   " +
                   $"<html xmlns='http://www.w3.org/1999/xhtml'>                                                                                                                                                                                                                                                      " +
                   $"<head>                                                                                                                                                                                                                                                                                           " +
                   $"<meta name='viewport' content='width=device-width' />                                                                                                                                                                                                                                            " +
                   $"<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />                                                                                                                                                                                                                            " +
                   $"<title>FCI Valle del Cauca</title>                                                                                                                                                                                                                                                 " +
                   $"</head>                                                                                                                                                                                                                                                                                          " +
                   $"<body style='margin:0px; background: #f8f8f8; '>                                                                                                                                                                                                                                                 " +
                   $"<div width='100%' style='background: #f8f8f8; padding: 0px 0px; font-family:arial; line-height:28px; height:100%;  width: 100%; color: #514d6a;'>                                                                                                                                                " +
                   $"  <div style='max-width: 700px; padding:50px 0;  margin: 0px auto; font-size: 14px'>                                                                                                                                                                                                             " +
                   $"    <table border='0' cellpadding='0' cellspacing='0' style='width: 100%; margin-bottom: 20px'>                                                                                                                                                                                                  " +
                   $"      <tbody>                                                                                                                                                                                                                                                                                    " +
                   $"        <tr>                                                                                                                                                                                                                                                                                     " +
                   $"          <td style='vertical-align: top; padding-bottom:15px;' align='center'><a href='https://www.fcivalledelcauca.com.co/' target='_blank'><img src='https://www.fcivalledelcauca.com.co/assets/images/home/fcivalle.png' alt='FCI Valle del Cauca' style='border:none; width:70%'><br/>      " +
                   $"        </tr>                                                                                                                                                                                                                                                                                    " +
                   $"      </tbody>                                                                                                                                                                                                                                                                                   " +
                   $"    </table>                                                                                                                                                                                                                                                                                     " +
                   $"    <table border='0' cellpadding='0' cellspacing='0' style='width: 100%;'>                                                                                                                                                                                                                      " +
                   $"      <tbody>                                                                                                                                                                                                                                                                                    " +
                   $"        <tr>                                                                                                                                                                                                                                                                                     " +
                   $"          <td style='background:#09972F; padding:20px; color:#fff; text-align:center;'> Hola: <b>{usuario.ToUpper()} <b>. </td>                                                                                                                                                        " +
                   $"        </tr>                                                                                                                                                                                                                                                                                    " +
                   $"      </tbody>                                                                                                                                                                                                                                                                                   " +
                   $"    </table>                                                                                                                                                                                                                                                                                     " +
                   $"    <div style='padding: 40px; background: #fff;'>                                                                                                                                                                                                                                               " +
                   $"      <table border='0' cellpadding='0' cellspacing='0' style='width: 100%;'>                                                                                                                                                                                                                    " +
                   $"        <tbody>                                                                                                                                                                                                                                                                                  " +
                   $"          <tr>                                                                                                                                                                                                                                                                                   " +
                   $"            <td>                                                                                                                                                                                                                                                                                 " +
                   $"              <p>Bienvenido al Micrositio Web del Proyecto de Fortalecimiento de las Capacidades Institucionales.</p>" +
                   $"               <p>Queremos darle la Bienvenida al Módulo de Capacitación.</p>                                                                                                                                                                                                                      " +
                   $"              <b>Cordialmente, Fortalecimiento de las Capacidades Institucionales</b> </td>                                                                                                                                                                                                                                     " +
                   $"          </tr>                                                                                                                                                                                                                                                                                  " +
                   $"		  <tr>                                                                                                                                                                                                                                                                                     " +
                   $"           <td  style='border-top:1px solid #f6f6f6; padding-top:20px; color:#777'>Si tienes alguna duda comunícate con la línea de atención 310 430 50 00.</td>                                                                                                     </tr>                       " +
                   $"        </tbody>                                                                                                                                                                                                                                                                                 " +
                   $"      </table>                                                                                                                                                                                                                                                                                   " +
                   $"    </div>                                                                                                                                                                                                                                                                                       " +
                   $"                                                                                                                                                                                                                                                                                                 " +
                   $"  </div>                                                                                                                                                                                                                                                                                         " +
                   $"</div>                                                                                                                                                                                                                                                                                           " +
                   $"</body>                                                                                                                                                                                                                                                                                          " +
                   $"</html>                                                                                                                                                                                                                                                                                          ";



        }

        public string HtmlContenchangerol(string email, string usuario,string rol)
        {
            return $"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>																																										   " +
                   $"<html xmlns='http://www.w3.org/1999/xhtml'>                                                                                                                                                                                                                                                      " +
                   $"<head>                                                                                                                                                                                                                                                                                           " +
                   $"<meta name='viewport' content='width=device-width' />                                                                                                                                                                                                                                            " +
                   $"<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />                                                                                                                                                                                                                            " +
                   $"<title>Eliteadmin Responsive web app kit</title>                                                                                                                                                                                                                                                 " +
                   $"</head>                                                                                                                                                                                                                                                                                          " +
                   $"<body style='margin:0px; background: #f8f8f8; '>                                                                                                                                                                                                                                                 " +
                   $"<div width='100%' style='background: #f8f8f8; padding: 0px 0px; font-family:arial; line-height:28px; height:100%;  width: 100%; color: #514d6a;'>                                                                                                                                                " +
                   $"  <div style='max-width: 700px; padding:50px 0;  margin: 0px auto; font-size: 14px'>                                                                                                                                                                                                             " +
                   $"    <table border='0' cellpadding='0' cellspacing='0' style='width: 100%; margin-bottom: 20px'>                                                                                                                                                                                                  " +
                   $"      <tbody>                                                                                                                                                                                                                                                                                    " +
                   $"        <tr>                                                                                                                                                                                                                                                                                     " +
                   $"          <td style='vertical-align: top; padding-bottom:15px;' align='center'><a href='https://www.fcivalledelcauca.com.co/' target='_blank'><img src='https://www.fcivalledelcauca.com.co/assets/images/home/fcivalle.png' alt='FCI Valle del Cauca' style='border:none; width:70%'><br/>      " +
                   $"        </tr>                                                                                                                                                                                                                                                                                    " +
                   $"      </tbody>                                                                                                                                                                                                                                                                                   " +
                   $"    </table>                                                                                                                                                                                                                                                                                     " +
                   $"    <table border='0' cellpadding='0' cellspacing='0' style='width: 100%;'>                                                                                                                                                                                                                      " +
                   $"      <tbody>                                                                                                                                                                                                                                                                                    " +
                   $"        <tr>                                                                                                                                                                                                                                                                                     " +
                   $"          <td style='background:#E38D2F; padding:20px; color:#fff; text-align:center;'> Hola: <b>{usuario.ToUpper()} <b>. </td>                                                                                                                                                        " +
                   $"        </tr>                                                                                                                                                                                                                                                                                    " +
                   $"      </tbody>                                                                                                                                                                                                                                                                                   " +
                   $"    </table>                                                                                                                                                                                                                                                                                     " +
                   $"    <div style='padding: 40px; background: #fff;'>                                                                                                                                                                                                                                               " +
                   $"      <table border='0' cellpadding='0' cellspacing='0' style='width: 100%;'>                                                                                                                                                                                                                    " +
                   $"        <tbody>                                                                                                                                                                                                                                                                                  " +
                   $"          <tr>                                                                                                                                                                                                                                                                                   " +
                   $"            <td>                                                                                                                                                                                                                                                                                 " +
                   $"              <p>Te comunicamos que tu perfíl de usuario ha cambiado, inicia sesión de nuevo en el portal web.</p>                                                                                                                                                                                                                " +
                   $"              <b>Cordialmente, Fortalecimiento de las Capacidades Institucionales</b> </td>                                                                                                                                                                                                                                     " +
                   $"          </tr>                                                                                                                                                                                                                                                                                  " +
                   $"		  <tr>                                                                                                                                                                                                                                                                                     " +
                   $"           <td  style='border-top:1px solid #f6f6f6; padding-top:20px; color:#777'>Si tienes alguna duda comunícate con la línea de atención 310 430 50 00.</td>                                                                                                     </tr>                       " +
                   $"        </tbody>                                                                                                                                                                                                                                                                                 " +
                   $"      </table>                                                                                                                                                                                                                                                                                   " +
                   $"    </div>                                                                                                                                                                                                                                                                                       " +
                   $"                                                                                                                                                                                                                                                                                                 " +
                   $"  </div>                                                                                                                                                                                                                                                                                         " +
                   $"</div>                                                                                                                                                                                                                                                                                           " +
                   $"</body>                                                                                                                                                                                                                                                                                          " +
                   $"</html>                                                                                                                                                                                                                                                                                          ";



        }
    }
}

